import type { Random } from '../persona';

/**
 * What a locale supplies, and the seam every locale is built against.
 *
 * ## Why the data is combinatorial rather than enumerated
 *
 * A corpus of ten thousand written-out people would be ten thousand people, and
 * the eight-name placeholder it replaced repeated on the ninth fill. Neither is
 * what a tester needs. Names, streets and organisations are therefore held as
 * *parts* and combined: a few hundred given names against a few hundred
 * surnames is tens of thousands of people, and a hundred street stems against
 * eight suffixes is eight hundred streets — from data small enough that somebody
 * can actually read it in a diff and notice a mistake.
 *
 * ## Real places, invented people
 *
 * Cities, regions and postal districts are **real**, because that is the only
 * way `Bristol / BS1` — or here `Winterthur / 8400` — is coherent rather than
 * decorative, and a tester checking address validation needs the pair to be one
 * a validator accepts. They are also facts, published openly, and carry no
 * licence to track.
 *
 * People, streets and organisations are **invented**. No real person's details
 * can come out of this, which is the line §4's non-goal draws: this is a fake
 * data tool, and "fake" has to survive contact with a large corpus.
 *
 * ## Formatting lives with its locale
 *
 * Phone numbers, postal codes and national identifiers are generated by the
 * locale that defines them rather than by a switch elsewhere. Everything about
 * de-CH is in one file, so adding a third locale is a file rather than an audit.
 */

export type Locale = 'en-US' | 'de-CH';

/** Every locale the corpus ships. Ordered as the options page will list them. */
export const LOCALES: readonly Locale[] = ['en-US', 'de-CH'];

/**
 * One real place, with everything about it that has to agree.
 *
 * `postalPrefix` rather than a whole code: a city owns a range, and generating
 * within it is what makes two personas from the same city differ without either
 * of them being wrong.
 */
export type Place = {
  readonly locality: string;
  /** The full name a form's "state" or "canton" field expects. */
  readonly region: string;
  /** The abbreviation the same field expects when it is a select. */
  readonly regionCode: string;
  readonly postalPrefix: string;
};

export type Corpus = {
  readonly locale: Locale;
  readonly country: string;
  readonly countryCode: string;

  readonly firstNames: readonly string[];
  readonly lastNames: readonly string[];
  /** Combined with `streetSuffixes`; neither is a street on its own. */
  readonly streetStems: readonly string[];
  readonly streetSuffixes: readonly string[];
  readonly organisationStems: readonly string[];
  readonly organisationSuffixes: readonly string[];
  readonly jobTitles: readonly string[];
  readonly places: readonly Place[];

  /** How this locale writes a street line, which is not the same everywhere. */
  readonly streetLine: (street: string, number: number) => string;
  /** A postal code inside the place's own district. */
  readonly postalCode: (place: Place, random: Random) => string;
  /** A mobile number in this country's own format, in international form. */
  readonly phone: (random: Random) => string;
  /**
   * The national identifier a form in this country asks for, or `undefined`
   * where the locale has none this project is willing to emit.
   */
  readonly nationalId: ((random: Random) => string) | undefined;
  /** A bank account number in this country's IBAN form, or `undefined`. */
  readonly iban: ((random: Random) => string) | undefined;
};

/**
 * `Math.floor(random() * length)`, never `* (length - 1)`.
 *
 * The reference's arithmetic makes the last entry of every array unreachable
 * (D7), which on a corpus this size means silently losing hundreds of entries
 * rather than one.
 */
export function pick<T>(items: readonly T[], random: Random): T {
  return items[Math.floor(random() * items.length)] as T;
}

/** A whole number in `[low, high]`, inclusive at both ends for the same reason. */
export function between(low: number, high: number, random: Random): number {
  return low + Math.floor(random() * (high - low + 1));
}

export function digits(count: number, random: Random): string {
  return Array.from({ length: count }, () => String(between(0, 9, random))).join('');
}

/**
 * The check digit for a Swiss AHV number, by EAN-13's rule.
 *
 * Exported because the tests verify it with an independent implementation:
 * checking a generator's arithmetic with the generator's own arithmetic proves
 * only that it is consistent with itself.
 */
export function ean13CheckDigit(body: string): number {
  let sum = 0;
  for (const [index, character] of [...body].entries()) {
    // Weights alternate 1,3 from the left across the twelve digits.
    sum += Number(character) * (index % 2 === 0 ? 1 : 3);
  }
  return (10 - (sum % 10)) % 10;
}

/**
 * The two check digits of an IBAN, by ISO 13616's mod-97 rule.
 *
 * Computed over the rearranged string with letters expanded to numbers, in
 * chunks — the whole value overflows a JavaScript number long before the end,
 * and an IBAN generator that silently loses precision produces numbers a bank's
 * validator rejects, which is exactly the defect this exists to avoid.
 */
export function ibanCheckDigits(countryCode: string, bban: string): string {
  const rearranged = `${bban}${countryCode}00`;
  const expanded = [...rearranged]
    .map((character) => (/[A-Z]/.test(character) ? String(character.charCodeAt(0) - 55) : character))
    .join('');

  let remainder = 0;
  for (const character of expanded) {
    remainder = (remainder * 10 + Number(character)) % 97;
  }
  return String(98 - remainder).padStart(2, '0');
}
